version: '3'
services:
  flask-upload:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/mingyao/flask_uploads:/app/uploads
    container_name: flask-upload-container
    restart: unless-stopped
